#.coveralls.yml

service_name: travis-ci

coverage_clover:
  - bookshelf/build/logs/clover.xml
  - helloworld/silex/build/logs/clover.xml

json_path: build/logs/coveralls-upload.json
exclude_no_stmt: true
