#.coveralls.yml

service_name: travis-ci

coverage_clover:
  - app-engine-flexible/1-hello-world/build/logs/clover.xml
  - app-engine-flexible/2-structured-data/build/logs/clover.xml
  - app-engine-flexible/3-cloud-storage/build/logs/clover.xml
  - app-engine-flexible/4-auth/build/logs/clover.xml
  - app-engine-flexible/5-logging/build/logs/clover.xml
  - app-engine-flexible/6-pubsub/build/logs/clover.xml
  - container-engine/build/logs/clover.xml
  - compute-engine/build/logs/clover.xml

json_path: build/logs/coveralls-upload.json
exclude_no_stmt: true
