#.coveralls.yml

service_name: travis-ci

coverage_clover:
  - 1-hello-world/build/logs/clover.xml
  - 2-structured-data/build/logs/clover.xml
  - 3-cloud-storage/build/logs/clover.xml
  - 4-auth/build/logs/clover.xml
  - 5-logging/build/logs/clover.xml
  - 6-pubsub/build/logs/clover.xml
  - optional-container-engine/build/logs/clover.xml
  - optional-compute-engine/build/logs/clover.xml

json_path: build/logs/coveralls-upload.json
exclude_no_stmt: true
