runtime: php72

env_variables:
    # In order to enable 3-legged OAuth, you must specify Client Credentials
    GOOGLE_CLIENT_ID:
    GOOGLE_CLIENT_SECRET:

    # populate these to use the CloudSQL backend
    CLOUDSQL_DATABASE_NAME:
    CLOUDSQL_PORT:
    CLOUDSQL_CONNECTION_NAME:
    CLOUDSQL_USER:
    CLOUDSQL_PASSWORD:
