# The Google App Engine php runtime is Debian Jessie with PHP installed
# and various os-level packages to allow installation of popular PHP
# libraries. The source is on github at:
#   https://github.com/GoogleCloudPlatform/php-docker
FROM gcr.io/google_appengine/php

# Add our php.ini config
ENV PHP_INI_OVERRIDE=config/php-pubsub.ini

# override the default CMD for the pubsub worker
CMD php bin/pubsub/entrypoint.php
